---
title: "Analizando el dataset Census Income"
author: "Marta Gómez y Braulio Vargas"
date: "3 de junio de 2016"
lang: es
output: 
  pdf_document:
    fig_caption: yes
    includes:
      in_header: structure.tex
    number_sections: yes
    toc: yes
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	cache=TRUE
)
```

# Definición del problema a resolver y enfoque elegido

La base de datos escogida se denomina _Census Income_, aunque también es conocida como _Adult_. Se puede descargar [aquí](http://archive.ics.uci.edu/ml/datasets/Census+Income "aqui"). Esta base de datos tiene 48842 instancias, cada una con 14 atributos. El problema es que también tiene valores perdidos. Para este trabajo, usaremos el paquete de `R` llamado `arules`, que contiene incluye esta base de datos.

El problema consiste en predecir cuando una persona va a gastarse más de $50K basándonos en los datos del censo. Por tanto, estamos ante un problema de _clasificación_.

Los atributos de los que disponemos son:

(Marta hace desde age hasta ocupation y Braulio desde relationship hasta income).

* _age_: 

* ___relationship___: variable que contiene el valor que puede tomar la relación de una persona con respecto a otra dentro de una familia. Contiene solo un valor por instancia del dato. Estos valores pueden ser _Wife_ (Esposa), _Own-child_ (hijo propio), _Husband_ (marido), _Not-in-family_ (sin familia), _Other-relative_ (otro tipo de familiar) y _Unmarried_ (soltero).
* ___race___: valor que describe la raza de la persona. Puede ser _White_ (Blanco), _Asian-Pac-Islander_ (asíatico o de las islas del pacífico), _Amer-Indian-Eskimo_ (indio americano o esquimal), _Other_ (otro) y _Black_ (negro).

* ___sex___: sexo de la persona, _Female_ (mujer) o _Male_ (hombre).

* ___capital-gain___: registro de la ganancia de capital de la persona.

* ___capital-lost___: registro de la pérdida de capital de la persona.

* ___hours-per-week___: corresponde a las horas de trabajo a la semana.

* ___country___: país de pertenencia. En este caso, hay una mayor variedad de valores, siendo los siguientes: _United-States_, _Cambodia_, _England_, _Puerto-Rico_, _Canada_, _Germany_, _Outlying-US(Guam-USVI-etc)_, _India_, _Japan_, _Greece_, _South_, _China_, _Cuba_, _Iran_, _Honduras_, _Philippines_, _Italy_, _Poland_, _Jamaica_, _Vietnam_, _Mexico_, _Portugal_, _Ireland_, _France_, _Dominican-Republic_, _Laos_, _Ecuador_, _Taiwan_, _Haiti_, _Columbia_, _Hungary_, _Guatemala_, _Nicaragua_, _Scotland_, _Thailand_, _Yugoslavia_, _El-Salvador_, _Trinadad&Tobago_, _Peru_, _Hong_, _Holand-Netherlands_,  o lo que es lo mismo, Estados-Unidos, Colombia, Inglaterra, Puerto-Rico, Canada, Alemania, Estados supervisados de los Estados Unidos, India, Japón, Grecia, Sudáfrica, China, Cuba, Irán, Honduras, Filipinas, Italia, Polonia, Jamaica, Vietnam, México, Portugal, Irlanda, Francia, República Dominicana, Laos, Ecuador, Taiwn, Haití, Colombia, Hungría, Guatemala, Nicaragua, Escocia, Tailandia, Yugoslavia, El Salvador y Trinidad-Tobago.

# Codificación de los datos de entrada para hacerlos útiles a los algoritmos

# Valoración del interés de las variables para el problema y selección de un subconjunto

# Normalización de las variables

# Selección de las técnicas y valoración de la idoneidad de las mismas frente a otras alternativas

# Aplicación de la técnica

## Estimación de los parámetros

## Estimación de los hiperparámetros

## Error de generalización

# Idoneidad de la función de regularización usada

# Valoración de resultados

# Justificación de la solución obtenida en base a la ténica usada y los datos.

## Dimensión VC del modelo

## Error de generalización del modelo

## Curva de aprendizaje del modelo
